### ISSUE TITLE
Missing setting "TargetBlank" and "RelNofollow" in Inspector view

### ISSUE THREAD

**Issue by brachycera** [sitegeist/Sitegeist.Archaeopteryx#38]
Thanks for the nice Link-Editor!

Am I missing something or is it not possible to activate the options  "TargetBlank" and "RelNofollow" in the Inspector view?

```yaml
  inspector:
    group: 'image'
    editor: 'Sitegeist.Archaeopteryx/Inspector/Editors/LinkEditor'
    editorOptions:
      # doesn't work
      # linking:
         #  relNofollow: true
         # targetBlank: true
      linkTypes:
        # doesn't work
        # 'Sitegeist.Archaeopteryx:Web':
         #  relNofollow: true
         # targetBlank: true
        'Sitegeist.Archaeopteryx:PhoneNumber':
          enabled: false
```

**Comment by brachycera** [comment]
@Benjamin-K Thanks for the reply and the clarification :wink:. I was just wondering because when I used the Link editor with the inline editor the options "TargetBlank" and "RelNofollow" worked:
```yaml
inline:
  editorOptions: 
    linking:
      'Sitegeist.Archaeopteryx':
        linkTypes:
          'Sitegeist.Archaeopteryx:PhoneNumber':
            enabled: false
      relNofollow: true
      targetBlank: true
```

But when I used it in the inspector, the Link editor didn't showed the options. But separate properties will of course do the job.
