### ISSUE TITLE
BUG: Overlay / stacked dialog issue with Sitegeist.Archaeopteryx Editor in Neos UI 8.3.1^

### ISSUE THREAD

**Issue by crydotsnake** [sitegeist/Sitegeist.Archaeopteryx#39]
### Description

When creating a link with the Sitegeist.Archaeopteryx Editor the Link overlay from the editor is stacked under the UI overlay. But the link overlay should be displayed first.

### Steps to Reproduce

1. Install (https://github.com/sitegeist/Sitegeist.Archaeopteryx)
2. Adjust your NodeType for example the TextWithImage NodeType:
 
```yaml
    link:
      type: string
      ui:
        label: Link
        showInCreationDialog: true
        help:
          message: 'Create a link'
        inspector:
          editor: 'Sitegeist.Archaeopteryx/Inspector/Editors/LinkEditor'
```

3. Try too create a link.

#### Expected behavior

The overlay of from the Archaeopteryx editor should be at the first.

#### Actual behavior

The link overlay from the Archaeopteryx gets stacked under the UI overlay

https://github.com/neos/neos-ui/assets/39345336/8b641deb-7496-4ad4-8f94-e54b83c87f5d

[What actually happened]

### Affected Versions

Neos: 8.3

UI: 8.3.3

You can get this information by running `composer show` or using the package management module within Neos.
The UI version can also be found inside the left sidebar after version 1.0.3.

_Originally posted by @crydotsnake in https://github.com/neos/neos-ui/issues/3583_
