### ISSUE TITLE
Turn off some editors

### ISSUE THREAD

**Issue by jonnitto** [sitegeist/Sitegeist.Archaeopteryx#4]
It would be nice of an editor could be turned of:

```yaml
editor: 'Sitegeist.Archaeopteryx/Inspector/Editors/LinkEditor'
editorOptions:
  linkTypes:
    'Sitegeist.Archaeopteryx:Node': false
    'Sitegeist.Archaeopteryx:MailTo': false
```
