### ISSUE TITLE
Does not work inside RichTextEditor

### ISSUE THREAD

**Issue by lorenzulrich** [sitegeist/Sitegeist.Archaeopteryx#56]
If you use a property with the `RichTextEditor`, you cannot set a link because the link editor modal is behind the Rich Text Editor.

## How to test

* Configure a RTE property:

```
    foo:
      type: string
      ui:
        label: 'Foo'
        reloadIfChanged: true
        inspector:
          group: foo
          editor: 'Neos.Neos/Inspector/Editors/RichTextEditor'
          editorOptions:
            linking:
              'Sitegeist.Archaeopteryx':
                linkTypes:
                  'Sitegeist.Archaeopteryx:Node':
                    allowedNodeTypes: ['My.Site:Document.Mixin.LinkablePage']
```

* Open the RTE
* Try adding a link
