### ISSUE TITLE
BUG: Login-Overlay pops up when trying to edit a link (1.4.x)

### ISSUE THREAD

**Issue by Benjamin-K** [sitegeist/Sitegeist.Archaeopteryx#69]
Since updating to Version 1.4.1, as soon as we click on a node with a link in the sidebar or try to add/edit a link in the inline editor, the login overlay pops up. 

We have already tried to (re)add the new privilegeTarget to some of our roles with no success. But it looks like the privileges are not applied correctly.

**Comment by lcherpit** [comment]
Same behavior here with Archaeopteryx 1.4.2 with Neos UI version: 8.3.10 Authenticated as Neos.Neos:Administrator,. 

It's seems like the security framework doesn't knows where the request come from. 
As a test, by giving more open rights like below, it works. 

```yaml
roles:
  'Neos.Flow:Everybody':
    privileges:
      - privilegeTarget: 'Sitegeist.Archaeopteryx:ApiAccess'
        permission: GRANT
```

How to find out more ?
