### ISSUE TITLE
Different options between Sidebar properties and RichTextEditor

### ISSUE THREAD

**Issue by Benjamin-K** [sitegeist/Sitegeist.Archaeopteryx#81]
Currently, the allowed options a developer can set are different between Links in inline editable content (RichText editor) and properties edited in the sidebar. 

| Sidebar | RichTextEditor |
|--------|--------|
| <img width="796" alt="Image" src="https://github.com/user-attachments/assets/fc798452-3a9d-40bb-9195-9ed7d200295b" /> | <img width="792" alt="Image" src="https://github.com/user-attachments/assets/eb34dc45-068e-46ab-a6f5-216117055d7f" /> |

As you can see, as a developer I am not able to enable the options `anchor`, `title`, `openInNewTab` or `rel="nofollow"` for properties in the sidebar. I'd expect to have the same options on both positions.

The yaml definition for the property in the sidebar currently is like this:

```yaml
# ...
editor: 'Sitegeist.Archaeopteryx/Inspector/Editors/LinkEditor'
editorOptions:
  linkTypes:
    'Sitegeist.Archaeopteryx:Node':
      anchor: true
    'Sitegeist.Archaeopteryx:Asset':
      anchor: true
```

So at least the `anchor` options **should** show up.
